### ISSUE TITLE
feat:  Reduce # of plonk constraints in the goldilocks range checker

### ISSUE THREAD

**Issue by kevjue** [succinctlabs/gnark-plonky2-verifier#31]
Use Miden's [approach](https://wiki.polygon.technology/docs/miden/design/stack/u32_ops/#checking-element-validity) for range checking that an element is within goldilocks.  

For the check that an element is not larger than `1111111111111111111111111111111100000000000000000000000000000000`, our current range checker is [adding up](https://github.com/succinctlabs/gnark-plonky2-verifier/blob/12fbb28fb60c188d6ab13892d0fd1186d6cd0a98/goldilocks/base.go#L304) all the most sig 32 bits and least sig 32 bits to verify most sig 32 bits != 2**32-1 or lst sig 32 bits == 0.

Miden is verifying that differently, which will remove all the adds.  We should do the same verification check that miden does.

**Comment by puma314** [comment]
Completed. Reduces the constraint count to ~20 million PLONK and ~6 million in Groth16.
