### ISSUE TITLE
Missing constraints in goldilocks `Reduce*`

### ISSUE THREAD

**Issue by shuklaayush** [succinctlabs/gnark-plonky2-verifier#40]
Looks like both `Reduce` and `ReduceWithMaxBits` functions are missing the actual `q*p + r == x` constraint
https://github.com/succinctlabs/gnark-plonky2-verifier/blob/89b5a01e4b4be8a439e28b864e36e0bb5b512207/goldilocks/base.go#L172-L216

I'm happy to create a PR

**Comment by jtguibas** [comment]
Hi @shuklaayush, thanks for flagging this. We actually also recently discovered this issue on our end through an audit and are thinking about fixing it. As a result, a PR is not needed.

Thank you for letting us know!
